"""Add passing_score and created_by to tests

Revision ID: add_passing_score_created_by
Revises: dc34406eb386
Create Date: 2026-04-01 18:08:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_passing_score_created_by'
down_revision = 'dc34406eb386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_score', sa.Integer(), nullable=True, default=50))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tests_created_by_users', 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tests_created_by_users', type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('passing_score')

    # ### end Alembic commands ###
